[package]
name = "power-bank"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.6.0"
embedded-text = "0.5.0"
profont = "0.7.0"